<<<<<<< HEAD
version: '3'
=======

>>>>>>> 6a4165e (add plugin redis)
services:
  php:
    container_name: php-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
<<<<<<< HEAD
    depends_on:
=======
    depends_on: # wait until mysql start
>>>>>>> 6a4165e (add plugin redis)
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: sandirahasia
      MYSQL_DATABASE: wordpress_dp
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: sandi_wordpress
    volumes:
      - ./mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
<<<<<<< HEAD
    container_name: redis-server
=======
    container_name: redis-server
>>>>>>> 6a4165e (add plugin redis)
